import Head from 'next/head'
import { View, Text } from 'react-native'
import { HomeScreen } from 'app/features/home/screen'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <View className="bg-green-100">
          <Text className="text-3xl font-bold text-green-500 underline">Hello world!</Text>
        </View> */}
        <HomeScreen />
      </main>
    </>
  )
}
